import Head from "next/head";
import { GetStaticProps, InferGetStaticPropsType } from "next";

import styles from "@/styles/Home.module.scss";

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch(`https://restcountries.com/v3.1/all`);
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      countries: data,
    },
  };
};

export default function Home({
  countries,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  console.log(countries);
  return (
    <>
      <Head>
        <title>Country</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <section className={styles.header}>
            <input
              type="text"
              placeholder="Search for a country..."
              className={styles.searchBar}
            />
            <select name="continents" id="continents">
              <option value="" disabled selected hidden>
                Filter by Region
              </option>
              <option value="Africa">Africa</option>
              <option value="America">America</option>
              <option value="Asia">Asia</option>
              <option value="Europe">Europe</option>
              <option value="Oceania">Oceania</option>
            </select>
          </section>
          <section className={styles.countryView}>
            {countries.map((country: any) => {
              return (
                <div className={styles.card}>
                  <img src={country.flags.png} alt={country.name.common} />
                  {/* <Image
                    priority
                    src={country.flags.png}
                    className={styles.image}
                    height={144}
                    width={144}
                    alt={country.name.common}
                  /> */}
                  <div className={styles.textArea}>
                    <h2>{country.name.official}</h2>
                    <p>
                      <span>Population:</span> {country.population}
                    </p>
                    <p>
                      <span>Region: {country.region}</span>
                    </p>
                    <p>
                      <span>Capital: {country.capital}</span>
                    </p>
                  </div>
                </div>
              );
            })}
          </section>
        </div>
      </main>
    </>
  );
}
